# Namespace for multihoming: primary UDN + secondary UDN.
# Label makes this namespace use a UserDefinedNetwork as primary; pods attach secondary UDN via annotation.
apiVersion: v1
kind: Namespace
metadata:
  name: multihoming-demo
  labels:
    k8s.ovn.org/primary-user-defined-network: ""
