# Secondary network (NAD): same pod also gets an interface on this L2 segment.
# Multihoming = primary UDN (100.5.0.0/24) + this secondary (10.100.200.0/24).
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: l2-secondary
  namespace: multihoming-demo
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "l2-secondary",
      "type": "ovn-k8s-cni-overlay",
      "topology": "layer2",
      "subnets": "10.100.200.0/24",
      "netAttachDefName": "multihoming-demo/l2-secondary",
      "excludeSubnets": "10.100.200.0/29"
    }
