# OVN-Kubernetes secondary network (layer2) via NetworkAttachmentDefinition.
# Pods keep the default network and get an extra interface on this L2 segment.
# See: https://docs.redhat.com/en/documentation/openshift_container_platform/4.21/html/multiple_networks/secondary-networks
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: l2-secondary
  namespace: secondary-net-demo
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "l2-secondary",
      "type": "ovn-k8s-cni-overlay",
      "topology": "layer2",
      "subnets": "10.100.200.0/24",
      "netAttachDefName": "secondary-net-demo/l2-secondary",
      "excludeSubnets": "10.100.200.0/29"
    }
