# ClusterUserDefinedNetwork: label advertise: true so RouteAdvertisements advertises 10.10.10.0/24 to the bastion.
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: extranet
  labels:
    advertise: "true"
spec:
  namespaceSelector:
    matchLabels:
      network: "extranet"
  network:
    topology: Layer2
    layer2:
      role: Primary
      subnets:
        - "10.10.10.0/24"
      ipam:
        lifecycle: Persistent
