# One CUDN for both namespaces so they share subnet 100.20.0.0/24 and can reach each other.
# NetworkPolicy in np-udn-a then restricts: only np-udn-b can reach the server.
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: np-udn-shared
spec:
  namespaceSelector:
    matchLabels:
      udn-shared: "true"
  network:
    topology: Layer2
    layer2:
      role: Primary
      subnets:
        - "100.20.0.0/24"
      ipam:
        lifecycle: Persistent
