# Allow ingress to server pods in np-udn-a only from namespace np-udn-b.
# Pods in np-udn-b (e.g. client) can reach server; other namespaces cannot.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-server-from-np-udn-b
  namespace: np-udn-a
spec:
  podSelector:
    matchLabels:
      app: server
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              np-udn-demo: "b"
      ports:
        - protocol: TCP
          port: 8080
