# One UDN for this namespace. Pods get IPs from 100.20.0.0/24.
apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: udn-demo
  namespace: np-udn-demo
spec:
  topology: Layer2
  layer2:
    role: Primary
    subnets:
      - "100.20.0.0/24"
    ipam:
      lifecycle: Persistent
