# UserDefinedNetwork for np-udn-b. Pods get IPs from 100.21.0.0/24.
apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: udn-b
  namespace: np-udn-b
spec:
  topology: Layer2
  layer2:
    role: Primary
    subnets:
      - "100.21.0.0/24"
    ipam:
      lifecycle: Persistent
