# Example NetworkPolicy: allow only pods in this namespace; deny from other namespaces.
# Use this to lock down a UDN namespace (e.g. only allow ingress from same namespace).
# Apply after workloads are running; adjust podSelector as needed.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace-only
  namespace: udn-vm-demo
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
