# ClusterUserDefinedNetwork: 192.168.100.0/24 for pods reachable from the bastion.
# Uses a different subnet from the bastion network (192.168.20.0/24) so the bastion has no local route;
# the cluster advertises 192.168.100.0/24 via BGP and the bastion forwards traffic to the pod.
# Label export: "true" is required for RouteAdvertisements (advertise-cudns) to advertise this CUDN.
# Cluster-admin required to create.
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: cudn-bastion
  labels:
    export: "true"
spec:
  namespaceSelector:
    matchLabels:
      udn-bastion: "true"
  network:
    topology: Layer2
    layer2:
      role: Primary
      subnets:
        - "192.168.100.0/24"
      ipam:
        lifecycle: Persistent
