# RouteAdvertisements: single CR for default network + CUDNs with label advertise: true.
# Requires FRR + routeAdvertisements enabled on CNO and an FRRConfiguration with label use-for-advertisements: true.
# Fix from sample: ClusterUserDefineNetworks -> ClusterUserDefinedNetworks.
apiVersion: k8s.ovn.org/v1
kind: RouteAdvertisements
metadata:
  name: default
spec:
  targetVRF: ""
  advertisements:
    - PodNetwork
  nodeSelector: {}
  frrConfigurationSelector:
    matchLabels:
      use-for-advertisements: "true"
  networkSelectors:
    - networkSelectionType: DefaultNetwork
    - networkSelectionType: ClusterUserDefinedNetworks
      clusterUserDefinedNetworkSelector:
        networkSelector:
          matchLabels:
            advertise: "true"
